---
name: 🐛 Bug Report
description: Signaler un bug ou un problème
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description du Bug
      description: Description claire et concise du bug
      placeholder: "Décrivez le problème rencontré..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Étapes de Reproduction
      description: Comment reproduire le bug
      placeholder: |
        1. Aller sur '....'
        2. Cliquer sur '....'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement Attendu
      description: Ce qui devrait se passer
      placeholder: "Décrivez le comportement attendu..."

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Logs
      description: Ajoutez des captures d'écran ou des logs si applicable

  - type: dropdown
    id: os
    attributes:
      label: Système d'exploitation
      options:
        - Windows
        - macOS
        - Linux
        - Autre
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version de WhytChat
      placeholder: "e.g. 1.0.0"

  - type: textarea
    id: additional
    attributes:
      label: Contexte Additionnel
      description: Toute information supplémentaire
